### ISSUE TITLE
Creating chores

### ISSUE THREAD

**Issue by deeptiraj** [brianmaissy/WSMA#28]
There are a lot of time allocations required but it is unclear what each refers to - what is a sign-out dealine?

**Comment by brianmaissy** [comment]
Sorry, after working on the project for so long we forgot that it involves some domain-specific knowledge. To sign out of a shift basically means to announce that you will not be able to complete it. If a user Bob signs out of a shift Cooking, for example, it means he knows he will not be available to cook that night. He will not get the hours associated with that chore, and will have to make it up elsewhere. However, it is better than simply not showing up to cook, because the workshift manager has time to find someone else to take that shift. The sign-out deadline establishes how long before Cooking starts Bob must announce his sign-out. Maybe it will be set to 24, because the workshift manager needs a day to find a replacement. After that deadline, the sign-out option is no longer available.

In general though, you're right, this is an issue we have discussed. What we've basically done is create a user interface which is a window to the backend functionality. What we should do is create an interface which allows intuitive manipulation of shifts, making the common case easy. That may mean moving the sign-out-deadline and due-hours-after fields to a different part of the interface (advanced options, edit shift, or something), and using safe defaults for them.
